### ISSUE TITLE
Find better name for the package and DataFrameWithInfo object

### ISSUE THREAD

**Issue by alessiamarcolini** [HK3-Lab-Team/pd_extras#30]

**Comment by lorenz-gorini** [comment]
Random ideas to break the ice:
- PreFlow (preprocessing flow), 
- FrAnX (Frame Analysis Extended), 
- PreLib (Preprocessing Library), 
- MuFAnLib (Multiple Feature Analysis Library -> perché l'idea è di analizzare in modo automatico dataframe con molte features), 
- DATIn (Data Analysis Torch Interface)

**Comment by alessiamarcolini** [comment]
From an offline conversation, these are the proposed package names:
- CaFePro (Cached Feature Preprocessing)
- CaLMu (Cached anaLytics for Multiple feature preprocessing)
- FrAnX (Frame Analysis eXtended)
- FrAX (dataFrame Analysis eXtended)
